---
- name: Clean up Content Views
  hosts: "{{ satellite_ops_server_name | default('none') }}"
  gather_facts: false
  roles:
    - role: redhat.satellite.content_view_version_cleanup
      vars:
        satellite_username: "{{ satellite_ops_username }}"
        satellite_password: "{{ satellite_ops_password }}"
        satellite_server_url: "{{ satellite_ops_server_url }}"
        satellite_organization: "{{ satellite_ops_org_name }}"
        satellite_content_view_version_cleanup_keep: 5